# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('service_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('route_long_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('shape_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('stop_sequence', models.IntegerField()),
                ('stop_id', models.ForeignKey(db_column='stop_id', on_delete=django.db.models.deletion.CASCADE, to='api.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('trip_head_sign', models.CharField(max_length=255)),
                ('route_id', models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.CASCADE, to='api.Route')),
                ('service_id', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='api.Calender')),
                ('shape_id', models.ForeignKey(db_column='shape_id', on_delete=django.db.models.deletion.CASCADE, to='api.Shape')),
            ],
        ),
        migrations.AddField(
            model_name='stoptime',
            name='trip_id',
            field=models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, to='api.Trip'),
        ),
    ]
