# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='friday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calender',
            name='monday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calender',
            name='saturday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calender',
            name='start_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calender',
            name='sunday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calender',
            name='thursday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calender',
            name='tuesday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calender',
            name='wednesday',
            field=models.IntegerField(),
        ),
    ]
