# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180428_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_short_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
