# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-15 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_trip_trip_headsign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shape',
            unique_together=set([('shape_id', 'shape_pt_sequence')]),
        ),
        migrations.AlterUniqueTogether(
            name='stoptime',
            unique_together=set([('trip_id', 'stop_id')]),
        ),
    ]
