# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181210_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptime',
            name='arrival_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='departure_time',
            field=models.IntegerField(),
        ),
    ]
