# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-10 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181210_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='shape_id',
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Calender'),
        ),
        migrations.AddField(
            model_name='trip',
            name='shape',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Shape'),
        ),
    ]
