# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180428_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_head_sign',
            new_name='trip_headsign',
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
