# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-10 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180815_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stoptime',
            unique_together=set([('trip_id', 'stop_id', 'stop_sequence')]),
        ),
    ]
